name: Question
description: Ask a question
title: '[QUESTION] name-here'
labels:
  - question
body:
  - type: input
    id: question
    attributes:
      label: What do you want to ask?
    validations:
      required: true
